### ISSUE TITLE
VGGSoud Dataset

### ISSUE THREAD

**Issue by lihong1226** [GeWu-Lab/OGM-GE_CVPR2022#14]
Can you provided the original dataset of VGGSound? (Include audio and visual).Not the official cdv files.  
thx

**Comment by DTaoo** [comment]
Hi, as we are the third party to the official VGGSound, it could be difficult to release the whole dataset personally.  You can use the youtube-dl lib to download all the videos in VGGSound.

Best,
Di

**Comment by lihong1226** [comment]
I want to get your processed picture and voice data?
