### ISSUE TITLE
What is a vanilla fusion method?

### ISSUE THREAD

**Issue by seongq** [GeWu-Lab/OGM-GE_CVPR2022#28]
In your paper, I read "Baseline is an introduced vanilla fusion method that uses activation function to mark out the related feature component of one modality compared with another."
Can you explain or give me materials about "vanilla fusion"?

Nowadays, I study a multimodal learning, your paper is very helpful.

**Comment by echo0409** [comment]
Hi, thanks for your interest.
The "baseline" method in Table 1, is a method is to use activation function, like sigmoid, to mark out related feature, similar with Gated fusion (https://arxiv.org/pdf/1802.02892.pdf).

The use of this method is relatively limited, and  the concat fusion is more recomanded.
