### ISSUE TITLE
Modulation with the sum fusion method

### ISSUE THREAD

**Issue by patrontheo** [GeWu-Lab/OGM-GE_CVPR2022#33]
Hello,
Thanks a lot for your work.
I had a question about the sum fusion. When you compute the unimodal output, you divide by 2 the bias of each linear layer. I understand why we do that in the concatenation fusion, but why also in the summation?
```python
if args.fusion_method == 'sum':
            out_v = (torch.mm(v, torch.transpose(model.module.fusion_module.fc_y.weight, 0, 1)) +
                     model.module.fusion_module.fc_y.bias / 2)
            out_a = (torch.mm(a, torch.transpose(model.module.fusion_module.fc_x.weight, 0, 1)) +
                     model.module.fusion_module.fc_x.bias / 2)
```

Thank you

**Comment by echo0409** [comment]
Hi, thanks for your attention.
Sorry for this minor bug in the code. We have fixed it and thanks a lot.

**Comment by patrontheo** [comment]
Great, thanks
