### ISSUE TITLE
OGM-GE进行梯度调度所作用的参数选取问题（ train in main.py）

### ISSUE THREAD

**Issue by XuecWu** [GeWu-Lab/OGM-GE_CVPR2022#38]
首先感谢您的辛勤付出，我对于OGM-GE进行梯度调度所作用的参数选取存在一些疑问（ train in main.py）
line 132 - 151 in main.py

              if args.modulation_starts <= epoch <= args.modulation_ends: 
                for name, parms in model.named_parameters():
                    layer = str(name).split('.')[1]
                    if 'audio' in layer and len(parms.grad.size()) == 4: 
                        if args.modulation == 'OGM_GE':  # bug fixed
                            parms.grad = parms.grad * coeff_a + \
                                         torch.zeros_like(parms.grad).normal_(0, parms.grad.std().item() + 1e-8)
                        elif args.modulation == 'OGM':
                            parms.grad *= coeff_a

                    if 'visual' in layer and len(parms.grad.size()) == 4:
                        if args.modulation == 'OGM_GE':  # bug fixed
                            parms.grad = parms.grad * coeff_v + \
                                         torch.zeros_like(parms.grad).normal_(0, parms.grad.std().item() + 1e-8)
                        elif args.modulation == 'OGM':
                            parms.grad *= coeff_v
            else:
                pass

在这里我首先将name的值全部打印输出，得到的结果如下所示：

> fusion_module.fc_out.weight
fusion_module.fc_out.weight
fusion_module.fc_out.bias
fusion_module.fc_out.bias
audio_net.conv1.weight
audio_net.conv1.weight
audio_net.bn1.weight
audio_net.bn1.weight
audio_net.bn1.bias
audio_net.bn1.bias
audio_net.layer1.0.conv1.weight
audio_net.layer1.0.conv1.weight
audio_net.layer1.0.bn1.weight
audio_net.layer1.0.bn1.weight
audio_net.layer1.0.bn1.bias
audio_net.layer1.0.bn1.bias
audio_net.layer1.0.conv2.weight
audio_net.layer1.0.conv2.weight
audio_net.layer1.0.bn2.weight
audio_net.layer1.0.bn2.weight
audio_net.layer1.0.bn2.bias
audio_net.layer1.0.bn2.bias
audio_net.layer1.1.conv1.weight
audio_net.layer1.1.conv1.weight
audio_net.layer1.1.bn1.weight
audio_net.layer1.1.bn1.weight
audio_net.layer1.1.bn1.bias
audio_net.layer1.1.bn1.bias
audio_net.layer1.1.conv2.weight
audio_net.layer1.1.conv2.weight
audio_net.layer1.1.bn2.weight
audio_net.layer1.1.bn2.weight
audio_net.layer1.1.bn2.bias
audio_net.layer1.1.bn2.bias
audio_net.layer2.0.conv1.weight
audio_net.layer2.0.conv1.weight
audio_net.layer2.0.bn1.weight
audio_net.layer2.0.bn1.weight
audio_net.layer2.0.bn1.bias
audio_net.layer2.0.bn1.bias
audio_net.layer2.0.conv2.weight
audio_net.layer2.0.conv2.weight
audio_net.layer2.0.bn2.weight
audio_net.layer2.0.bn2.weight
audio_net.layer2.0.bn2.bias
audio_net.layer2.0.bn2.bias
audio_net.layer2.0.downsample.0.weight
audio_net.layer2.0.downsample.0.weight
audio_net.layer2.0.downsample.1.weight
audio_net.layer2.0.downsample.1.weight
audio_net.layer2.0.downsample.1.bias
audio_net.layer2.0.downsample.1.bias
audio_net.layer2.1.conv1.weight
audio_net.layer2.1.conv1.weight
audio_net.layer2.1.bn1.weight
audio_net.layer2.1.bn1.weight
audio_net.layer2.1.bn1.bias
audio_net.layer2.1.bn1.bias
audio_net.layer2.1.conv2.weight
audio_net.layer2.1.conv2.weight
audio_net.layer2.1.bn2.weight
audio_net.layer2.1.bn2.weight
audio_net.layer2.1.bn2.bias
audio_net.layer2.1.bn2.bias
audio_net.layer3.0.conv1.weight
audio_net.layer3.0.conv1.weight
audio_net.layer3.0.bn1.weight
audio_net.layer3.0.bn1.weight
audio_net.layer3.0.bn1.bias
audio_net.layer3.0.bn1.bias
audio_net.layer3.0.conv2.weight
audio_net.layer3.0.conv2.weight
audio_net.layer3.0.bn2.weight
audio_net.layer3.0.bn2.weight
audio_net.layer3.0.bn2.bias
audio_net.layer3.0.bn2.bias
audio_net.layer3.0.downsample.0.weight
audio_net.layer3.0.downsample.0.weight
audio_net.layer3.0.downsample.1.weight
audio_net.layer3.0.downsample.1.weight
audio_net.layer3.0.downsample.1.bias
audio_net.layer3.0.downsample.1.bias
audio_net.layer3.1.conv1.weight
audio_net.layer3.1.conv1.weight
audio_net.layer3.1.bn1.weight
audio_net.layer3.1.bn1.weight
audio_net.layer3.1.bn1.bias
audio_net.layer3.1.bn1.bias
audio_net.layer3.1.conv2.weight
audio_net.layer3.1.conv2.weight
audio_net.layer3.1.bn2.weight
audio_net.layer3.1.bn2.weight
audio_net.layer3.1.bn2.bias
audio_net.layer3.1.bn2.bias
audio_net.layer4.0.conv1.weight
audio_net.layer4.0.conv1.weight
audio_net.layer4.0.bn1.weight
audio_net.layer4.0.bn1.weight
audio_net.layer4.0.bn1.bias
audio_net.layer4.0.bn1.bias
audio_net.layer4.0.conv2.weight
audio_net.layer4.0.conv2.weight
audio_net.layer4.0.bn2.weight
audio_net.layer4.0.bn2.weight
audio_net.layer4.0.bn2.bias
audio_net.layer4.0.bn2.bias
audio_net.layer4.0.downsample.0.weight
audio_net.layer4.0.downsample.0.weight
audio_net.layer4.0.downsample.1.weight
audio_net.layer4.0.downsample.1.weight
audio_net.layer4.0.downsample.1.bias
audio_net.layer4.0.downsample.1.bias
audio_net.layer4.1.conv1.weight
audio_net.layer4.1.conv1.weight
audio_net.layer4.1.bn1.weight
audio_net.layer4.1.bn1.weight
audio_net.layer4.1.bn1.bias
audio_net.layer4.1.bn1.bias
audio_net.layer4.1.conv2.weight
audio_net.layer4.1.conv2.weight
audio_net.layer4.1.bn2.weight
audio_net.layer4.1.bn2.weight
audio_net.layer4.1.bn2.bias
audio_net.layer4.1.bn2.bias
visual_net.conv1.weight
visual_net.conv1.weight
visual_net.bn1.weight
visual_net.bn1.weight
visual_net.bn1.bias
visual_net.bn1.bias
visual_net.layer1.0.conv1.weight
visual_net.layer1.0.conv1.weight
visual_net.layer1.0.bn1.weight
visual_net.layer1.0.bn1.weight
visual_net.layer1.0.bn1.bias
visual_net.layer1.0.bn1.bias
visual_net.layer1.0.conv2.weight
visual_net.layer1.0.conv2.weight
visual_net.layer1.0.bn2.weight
visual_net.layer1.0.bn2.weight
visual_net.layer1.0.bn2.bias
visual_net.layer1.0.bn2.bias
visual_net.layer1.1.conv1.weight
visual_net.layer1.1.conv1.weight
visual_net.layer1.1.bn1.weight
visual_net.layer1.1.bn1.weight
visual_net.layer1.1.bn1.bias
visual_net.layer1.1.bn1.bias
visual_net.layer1.1.conv2.weight
visual_net.layer1.1.conv2.weight
visual_net.layer1.1.bn2.weight
visual_net.layer1.1.bn2.weight
visual_net.layer1.1.bn2.bias
visual_net.layer1.1.bn2.bias
visual_net.layer2.0.conv1.weight
visual_net.layer2.0.conv1.weight
visual_net.layer2.0.bn1.weight
visual_net.layer2.0.bn1.weight
visual_net.layer2.0.bn1.bias
visual_net.layer2.0.bn1.bias
visual_net.layer2.0.conv2.weight
visual_net.layer2.0.conv2.weight
visual_net.layer2.0.bn2.weight
visual_net.layer2.0.bn2.weight
visual_net.layer2.0.bn2.bias
visual_net.layer2.0.bn2.bias
visual_net.layer2.0.downsample.0.weight
visual_net.layer2.0.downsample.0.weight
visual_net.layer2.0.downsample.1.weight
visual_net.layer2.0.downsample.1.weight
visual_net.layer2.0.downsample.1.bias
visual_net.layer2.0.downsample.1.bias
visual_net.layer2.1.conv1.weight
visual_net.layer2.1.conv1.weight
visual_net.layer2.1.bn1.weight
visual_net.layer2.1.bn1.weight
visual_net.layer2.1.bn1.bias
visual_net.layer2.1.bn1.bias
visual_net.layer2.1.conv2.weight
visual_net.layer2.1.conv2.weight
visual_net.layer2.1.bn2.weight
visual_net.layer2.1.bn2.weight
visual_net.layer2.1.bn2.bias
visual_net.layer2.1.bn2.bias
visual_net.layer3.0.conv1.weight
visual_net.layer3.0.conv1.weight
visual_net.layer3.0.bn1.weight
visual_net.layer3.0.bn1.weight
visual_net.layer3.0.bn1.bias
visual_net.layer3.0.bn1.bias
visual_net.layer3.0.conv2.weight
visual_net.layer3.0.conv2.weight
visual_net.layer3.0.bn2.weight
visual_net.layer3.0.bn2.weight
visual_net.layer3.0.bn2.bias
visual_net.layer3.0.bn2.bias
visual_net.layer3.0.downsample.0.weight
visual_net.layer3.0.downsample.0.weight
visual_net.layer3.0.downsample.1.weight
visual_net.layer3.0.downsample.1.weight
visual_net.layer3.0.downsample.1.bias
visual_net.layer3.0.downsample.1.bias
visual_net.layer3.1.conv1.weight
visual_net.layer3.1.conv1.weight
visual_net.layer3.1.bn1.weight
visual_net.layer3.1.bn1.weight
visual_net.layer3.1.bn1.bias
visual_net.layer3.1.bn1.bias
visual_net.layer3.1.conv2.weight
visual_net.layer3.1.conv2.weight
visual_net.layer3.1.bn2.weight
visual_net.layer3.1.bn2.weight
visual_net.layer3.1.bn2.bias
visual_net.layer3.1.bn2.bias
visual_net.layer4.0.conv1.weight
visual_net.layer4.0.conv1.weight
visual_net.layer4.0.bn1.weight
visual_net.layer4.0.bn1.weight
visual_net.layer4.0.bn1.bias
visual_net.layer4.0.bn1.bias
visual_net.layer4.0.conv2.weight
visual_net.layer4.0.conv2.weight
visual_net.layer4.0.bn2.weight
visual_net.layer4.0.bn2.weight
visual_net.layer4.0.bn2.bias
visual_net.layer4.0.bn2.bias
visual_net.layer4.0.downsample.0.weight
visual_net.layer4.0.downsample.0.weight
visual_net.layer4.0.downsample.1.weight
visual_net.layer4.0.downsample.1.weight
visual_net.layer4.0.downsample.1.bias
visual_net.layer4.0.downsample.1.bias
visual_net.layer4.1.conv1.weight
visual_net.layer4.1.conv1.weight
visual_net.layer4.1.bn1.weight
visual_net.layer4.1.bn1.weight
visual_net.layer4.1.bn1.bias
visual_net.layer4.1.bn1.bias
visual_net.layer4.1.conv2.weight
visual_net.layer4.1.conv2.weight
visual_net.layer4.1.bn2.weight
visual_net.layer4.1.bn2.weight
visual_net.layer4.1.bn2.bias
visual_net.layer4.1.bn2.bias

按照layer = str(name).split('.')[1]这行代码可知，layer的取值应为fc_out, conv1, bn1, layer1.0, layer1.1 ... layer4.1
之后将执行if 'audio' in layer and len(parms.grad.size()) == 4:这行代码，可是按照上述运行出的结果，layer的取值中并没有包含'audio'的层，那么也就不会再执行后续的操作，整体的调度也不再会起作用。

我不知道是我的理解有问题还是在哪一步的操作上出现了失误，请作者给予指正和意见。期待您的回复，再次感谢您的辛勤付出！

**Comment by echo0409** [comment]
Hi,

thanks for your attention to our work.

In fact, in our case, we use multiple GPUs, so the layer name is "module.visual_net.layer4.1.bn1.bias". And this code works well.

You could modify the code based on your setting.

**Comment by XuecWu** [comment]
@echo0409 Thank you for your reply.

**Comment by chenshu2000** [comment]
> Hi,
> 
> thanks for your attention to our work.
> 
> In fact, in our case, we use multiple GPUs, so the layer name is "module.visual_net.layer4.1.bn1.bias". And this code works well.
> 
> You could modify the code based on your setting.

what does “ len(parms.grad.size()) == 4 ” mean？thanks

**Comment by XuecWu** [comment]
@chenshu2000  As far as I am concerned, it represents the shape of the specific tensor.
