### ISSUE TITLE
Some question about sgd noise distribution

### ISSUE THREAD

**Issue by Franklee95** [GeWu-Lab/OGM-GE_CVPR2022#5]
Hi. Formula(16) in paper note that sgd noise have Gaussian distribution like this:h(θ)~N (0, Σsgd(θ)).
Howerver.in "main.py" at line 128-130 shows like this:
```python
parms.grad *= coeff_a
if args.modulation == 'OGM_GE':
    parms.grad += torch.zeros_like(parms.grad).normal_(0, parms.grad.std().item() + 1e-8)
```
after multiplying the `coeff_a`(or in paper is `ku`),the variance of `parms.grad` becomes ku* ku* Σsgd(θ) rather than Σsgd(θ).
So whether 'Σsgd(θ)' or 'ku* ku* Σsgd(θ)' is the right variance of noise distribution? Thanks for your reply!

**Comment by echo0409** [comment]
Thanks for your question. If X~N(0, sigma), then k*X~N(0,k^2*sigma). Hence, the coeff_a is 'k', and the coefficient of 'Σsgd(θ)' is k^2.
